name: whatsapp_status_saver
description: WhatsApp Status Saver
publish_to: 'none'
homepage: https://app.sadra.at/whatsapp-status-saver
repository: https://github.com/xsadra/whatsapp-status-saver.git
version: 1.0.0+3

environment:
  sdk: ">=2.13.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  avatar_view: ^1.0.1
  animations: ^2.0.1
#  fluttericon: 2.0.0
  path_provider: ^2.0.3
  get_it: ^7.2.0
  permission_handler: ^8.1.6
  dartz: ^0.10.0
  flutter_bloc: ^7.1.0
  video_player: ^2.2.0
  logger: ^1.1.0
  flick_video_player: ^0.3.1
  visibility_detector: ^0.2.0
  android_intent_plus: ^2.0.0
  url_launcher: ^6.0.10
  double_back_to_close_app: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
